# Generated by Django 5.1.4 on 2024-12-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatwellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('burgers', 'Burgers'), ('drinks', 'Drinks'), ('sides', 'Sides'), ('desserts', 'Desserts')], default='burgers', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.IntegerField(default=0, help_text='Weight in grams'),
        ),
    ]
