# Generated by Django 5.1.4 on 2024-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatwellapp', '0002_food_category_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('burgers', 'Burgers'), ('drinks', 'Drinks'), ('swallow', 'Swallow'), ('desserts', 'Desserts')], default='burgers', max_length=20),
        ),
    ]
