# Generated by Django 5.1.4 on 2024-12-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatwellapp', '0003_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('fast', 'Fast'), ('drinks', 'Drinks'), ('swallow', 'Swallow'), ('desserts', 'Desserts')], default='fast', max_length=20),
        ),
    ]
