# Generated by Django 5.1.4 on 2025-01-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatwellapp', '0005_supermarket_supermarketitem_supermarketorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarketorder',
            name='supermarket',
        ),
        migrations.RemoveField(
            model_name='supermarketitem',
            name='supermarket',
        ),
        migrations.RemoveField(
            model_name='supermarketorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supermarketorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='supermarketorderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Supermarket',
        ),
        migrations.DeleteModel(
            name='SupermarketItem',
        ),
        migrations.DeleteModel(
            name='SupermarketOrder',
        ),
        migrations.DeleteModel(
            name='SupermarketOrderItem',
        ),
    ]
